version: '3'

services:
  db:
    image: mariadb
    container_name: eagle_db
    environment:
      MYSQL_ROOT_PASSWORD: test
    restart: always
  eagle:
      image: nickzurich/efak
      container_name: eagle
      environment:
        EFAK_CLUSTER_ZK_LIST: 104.199.142.9:2181,35.229.251.246:2181,35.229.227.233:2181
        EFAK_DB_DRIVER: com.mysql.cj.jdbc.Driver
        EFAK_DB_URL: jdbc:mysql://db:3306/ke?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
        EFAK_DB_USERNAME: root
        EFAK_DB_PASSWORD: test
        EFAK_METRICS_CHARTS: "true"
        EFAK_CLUSTER_KAFKA_EAGLE_SASL_ENABLE: "true"
        EFAK_CLUSTER_KAFKA_EAGLE_SASL_PROTOCOL: "SASL_PLAINTEXT"
        EFAK_CLUSTER_KAFKA_EAGLE_SASL_MECHANISM: "PLAIN"
        EFAK_CLUSTER_KAFKA_EAGLE_SASL_JAAS_CONFIG: org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin";
      depends_on:
        - db
      ports:
        - 8048:8048
